<?xml version="1.0" encoding="utf-8"?><Database Name="sandbox" Class="SandboxDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=sandbox;Integrated Security=True" SettingsObjectName="Basic.Properties.Settings" SettingsPropertyName="sandboxConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Jobs" Member="Jobs">
    <Type Name="Job">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="JobName" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="Project_Job" Member="Project" ThisKey="ProjectId" OtherKey="id" Type="Project" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Projects" Member="Projects">
    <Type Name="Project">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProjectName" Type="System.String" DbType="NChar(100)" CanBeNull="true" />
      <Association Name="Project_Job" Member="Jobs" ThisKey="id" OtherKey="ProjectId" Type="Job" />
    </Type>
  </Table>
</Database>